services:
  # HAPROXY Load Balancer
  haproxy:
    image: haproxy:2.8
    container_name: haproxy-pepeling
    ports:
      - "80:80"
      - "443:443"
      - "8405:8405"  # Stats page untuk exporter
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl:/usr/local/etc/haproxy/ssl:ro
    networks:
      - haproxy-net
    restart: unless-stopped

networks:
  haproxy-net:
    driver: bridge
